# Generated by Django 5.2 on 2025-05-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
